library(dplyr)
library(magrittr)

#this file is designed to be run once to help prepare the data for import by the dashboard

# import R source generated by limesurvey
source("dashboard/data/survey_269999_R_syntax_file.R", encoding = "UTF-8", chdir = T)

# complete resposnes only
data %<>% filter(!is.na(submitdate), token != "test")
saveRDS(data, "dashboard/data/survey_completes.RDS")

#create template for qtypes.csv
meta <- read.table("dashboard/data/meta_data.txt", header = T, sep = "\t",
                   quote = "", stringsAsFactors = F, na.strings = "")
meta <- select(meta, which(!apply(meta, 2, function(x) all(is.na(x)))))

qtypes <- filter(meta, class == "Q") %>%
  mutate(shortname = name,
         segment = 0) %>%
  select(qid = name, shortname, type.scale, text, segment)

write.csv(qtypes, "dashboard/data/qtypes.csv")
